from datetime import datetime, timedelta, timezone
from .models import Alert, Building, EnergyBaseline, EnergyReading, Floor, HVACUnit, OccupancyReading, Organization, Room, Sensor, SensorReading, User
from .security import hash_password

DEMO_USERS = [
    ("superadmin@smarthvac.local", "Superadmin User", "SUPERADMIN"),
    ("admin@smarthvac.local", "Organization Admin", "ADMIN"),
    ("manager@smarthvac.local", "Facility Manager", "FACILITY_MANAGER"),
    ("employee@smarthvac.local", "Employee User", "EMPLOYEE"),
]

BUILDING_SEED = [
    ("BLD-001", "SmartHVAC Building 01", "12 Anna Salai", "Chennai", 13.0827, 80.2707),
    ("BLD-002", "SmartHVAC Building 02", "5 Mount Road", "Chennai", 13.0674, 80.2376),
    ("BLD-003", "SmartHVAC Building 03", "38 Velachery Main Road", "Chennai", 12.9815, 80.2180),
]

def seed_database(db) -> None:
    organization = db.query(Organization).filter_by(slug="demo-organization").first()
    if not organization:
        organization = Organization(name="SmartHVAC Demo Organization", slug="demo-organization")
        db.add(organization)
        db.flush()
    for email, name, role in DEMO_USERS:
        user = db.query(User).filter_by(email=email).first()
        if not user:
            user = User(email=email, name=name, role=role, password_hash=hash_password("demo1234"))
            db.add(user)
        user.role = role
        user.organization_id = None if role == "SUPERADMIN" else organization.id
    if db.query(Building).first():
        db.query(Building).filter(Building.organization_id.is_(None)).update({"organization_id": organization.id}, synchronize_session=False)
        db.commit()
        return
    for b_index, (code, name, address, city, latitude, longitude) in enumerate(BUILDING_SEED):
        building = Building(code=code, name=name, address=address, city=city, latitude=latitude, longitude=longitude, organization_id=organization.id)
        db.add(building)
        db.flush()
        for floor_number in range(1, 4):
            floor = Floor(building_id=building.id, name=f"Floor {floor_number}", floor_number=floor_number)
            db.add(floor)
            db.flush()
            for room_number in range(1, 7):
                room_code = f"{floor_number}{room_number:02d}"
                room = Room(floor_id=floor.id, code=room_code, name=f"Room {room_code}", capacity=12 + room_number * 4)
                db.add(room)
                db.flush()
                unit = HVACUnit(room_id=room.id, code=f"HVAC-{b_index + 1:02d}-{room_code}", setpoint=24.0, health=96 - b_index * 8 - room_number)
                db.add(unit)
                db.flush()
                temperature_sensor = Sensor(room_id=room.id, sensor_type="temperature", code=f"{building.code}-{room_code}-temperature")
                db.add(temperature_sensor)
                for sensor_type in ("humidity", "co2", "air_quality", "occupancy", "energy"):
                    db.add(Sensor(room_id=room.id, sensor_type=sensor_type, code=f"{building.code}-{room_code}-{sensor_type}"))
                db.flush()
                occupied = (room_number + floor_number + b_index) % 3 != 0
                occupancy = min(room.capacity, (6 + room_number * 2) if occupied else 0)
                temperature = 23.5 + b_index * 1.1 + (0.7 if occupied else -0.3)
                for hours_ago in range(0, 24 * 7, 6):
                    recorded = datetime.now(timezone.utc) - timedelta(hours=hours_ago)
                    db.add(SensorReading(room_id=room.id, sensor_id=temperature_sensor.id, metric="temperature", value=temperature + ((hours_ago % 8) - 4) * .05, recorded_at=recorded))
                    db.add(EnergyReading(room_id=room.id, power_kw=1.3 + occupancy / 70, energy_kwh=1.3 + occupancy / 70, recorded_at=recorded))
                    db.add(OccupancyReading(room_id=room.id, occupancy=occupancy, recorded_at=recorded))
                db.add(EnergyBaseline(room_id=room.id, baseline_kwh=20 + occupancy * .08))
    db.flush()
    first_building = db.query(Building).first()
    db.add(Alert(building_id=first_building.id, severity="WARNING", title="Airflow below baseline", message="HVAC-01-202 is using more runtime than its occupancy profile suggests.", status="OPEN"))
    db.add(Alert(building_id=first_building.id, severity="INFO", title="Demo mode enabled", message="Sensor readings are generated by the local simulator.", status="OPEN"))
    db.commit()
